# Generated by Django 2.2.9 on 2020-02-17 18:34

from django.db import migrations, models
import django.db.models.deletion

from posts.models import Post


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('comments', '0002_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parentPost',
            # I edited this manually to assign all existing comments prior to migration to the first post available.
            field=models.ForeignKey(default=Post.objects.first().id, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
            preserve_default=False,
        ),
    ]
