# Generated by Django 2.2.9 on 2020-03-19 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('friend_node', models.URLField(max_length=500, unique=True)),
                ('image_share', models.BooleanField(default=True)),
                ('post_share', models.BooleanField(default=True)),
            ],
        ),
    ]
