# Generated by Django 2.2.10 on 2020-03-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('foreign_server_hostname', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('foreign_server_username', models.CharField(max_length=500, unique=True)),
                ('foreign_server_password', models.CharField(max_length=500)),
                ('foreign_server_api_location', models.URLField(max_length=500)),
                ('username_registered_on_foreign_server', models.CharField(max_length=500)),
                ('password_registered_on_foreign_server', models.CharField(max_length=500)),
                ('image_share', models.BooleanField(default=True)),
                ('post_share', models.BooleanField(default=True)),
                ('append_slash', models.BooleanField(default=False)),
            ],
        ),
    ]
