# Generated by Django 2.1.5 on 2020-03-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_server_hostname', models.URLField(max_length=500, unique=True)),
                ('foreign_server_password', models.CharField(max_length=30)),
                ('hostname_registered_on_foreign_server', models.URLField(max_length=500)),
                ('password_registered_on_foreign_server', models.CharField(max_length=30)),
                ('image_share', models.BooleanField(default=True)),
                ('post_share', models.BooleanField(default=True)),
            ],
        ),
    ]
