# Generated by Django 2.1.5 on 2020-03-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20200320_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='foreign_server_hostname',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='hostname_registered_on_foreign_server',
            field=models.CharField(max_length=500),
        ),
    ]
