# Generated by Django 2.2.10 on 2020-03-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20200321_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='append_slash',
            field=models.BooleanField(default=False),
        ),
    ]
