# Generated by Django 2.2.10 on 2020-03-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20200321_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='foreign_server_username',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
