# Generated by Django 2.2.10 on 2020-04-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20200324_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='image_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='post_share',
            field=models.BooleanField(default=False),
        ),
    ]
