# Generated by Django 2.2.10 on 2020-03-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_node_append_slash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='image_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='post_share',
            field=models.BooleanField(default=False),
        ),
    ]
