# Generated by Django 2.2.10 on 2020-03-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_auto_20200329_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='foreign_server_username',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
