# Generated by Django 2.2.5 on 2020-03-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.CharField(max_length=500)),
                ('to_id', models.CharField(max_length=500)),
            ],
            options={
                'unique_together': {('from_id', 'to_id')},
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=500)),
                ('friend_id', models.CharField(max_length=500)),
            ],
            options={
                'unique_together': {('author_id', 'friend_id')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.CharField(max_length=500)),
                ('followee_id', models.CharField(max_length=500)),
            ],
            options={
                'unique_together': {('follower_id', 'followee_id')},
            },
        ),
    ]
