# Generated by Django 2.2.9 on 2020-02-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.URLField(max_length=500)),
                ('friend_id', models.URLField(max_length=500)),
            ],
            options={
                'unique_together': {('user_id', 'friend_id')},
            },
        ),
    ]
