# Generated by Django 2.2.9 on 2020-02-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.URLField(max_length=500)),
                ('to_id', models.URLField(max_length=500)),
            ],
            options={
                'unique_together': {('from_id', 'to_id')},
            },
        ),
    ]
