# Generated by Django 2.2.10 on 2020-03-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.URLField(max_length=500)),
                ('followee_id', models.URLField(max_length=500)),
            ],
            options={
                'unique_together': {('follower_id', 'followee_id')},
            },
        ),
    ]
