# Generated by Django 3.0.2 on 2020-01-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('bio', models.CharField(max_length=256)),
                ('host', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('display_name', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('github', models.CharField(max_length=256)),
            ],
        ),
    ]
