# Generated by Django 2.2.10 on 2020-03-19 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='followed_authors',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(related_name='_author_friends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.URLField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
