# Generated by Django 2.2.10 on 2020-03-04 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='author',
            name='friend_request',
        ),
    ]
