# Generated by Django 2.2.10 on 2020-03-19 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200319_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.URLField(max_length=500, primary_key=True, serialize=False, validators=[django.core.validators.URLValidator(schemes=['http'])]),
        ),
    ]
