# Generated by Django 2.2.10 on 2020-03-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200305_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
