# Generated by Django 2.2.9 on 2020-02-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200212_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.URLField(max_length=500),
        ),
    ]
