# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .post import Post  # noqa: F401,E501
from social_distribution.social_distribution import util


class ArrayOfPosts(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """ArrayOfPosts - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ArrayOfPosts':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ArrayOfPosts of this ArrayOfPosts.  # noqa: E501
        :rtype: ArrayOfPosts
        """
        return util.deserialize_model(dikt, cls)
