# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .comment import Comment  # noqa: F401,E501
from social_distribution.social_distribution import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, query: str=None, post: Comment=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param query: The query of this Body.  # noqa: E501
        :type query: str
        :param post: The post of this Body.  # noqa: E501
        :type post: Comment
        """
        self.swagger_types = {
            'query': str,
            'post': Comment
        }

        self.attribute_map = {
            'query': 'query',
            'post': 'post'
        }
        self._query = query
        self._post = post

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def query(self) -> str:
        """Gets the query of this Body.


        :return: The query of this Body.
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query: str):
        """Sets the query of this Body.


        :param query: The query of this Body.
        :type query: str
        """

        self._query = query

    @property
    def post(self) -> Comment:
        """Gets the post of this Body.


        :return: The post of this Body.
        :rtype: Comment
        """
        return self._post

    @post.setter
    def post(self, post: Comment):
        """Sets the post of this Body.


        :param post: The post of this Body.
        :type post: Comment
        """

        self._post = post
