# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from social_distribution.social_distribution import util


class FriendrequestFriend(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, host: str=None, display_name: str=None, url: str=None):  # noqa: E501
        """FriendrequestFriend - a model defined in Swagger

        :param id: The id of this FriendrequestFriend.  # noqa: E501
        :type id: str
        :param host: The host of this FriendrequestFriend.  # noqa: E501
        :type host: str
        :param display_name: The display_name of this FriendrequestFriend.  # noqa: E501
        :type display_name: str
        :param url: The url of this FriendrequestFriend.  # noqa: E501
        :type url: str
        """
        self.swagger_types = {
            'id': str,
            'host': str,
            'display_name': str,
            'url': str
        }

        self.attribute_map = {
            'id': 'id',
            'host': 'host',
            'display_name': 'displayName',
            'url': 'url'
        }
        self._id = id
        self._host = host
        self._display_name = display_name
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'FriendrequestFriend':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The friendrequest_friend of this FriendrequestFriend.  # noqa: E501
        :rtype: FriendrequestFriend
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this FriendrequestFriend.


        :return: The id of this FriendrequestFriend.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this FriendrequestFriend.


        :param id: The id of this FriendrequestFriend.
        :type id: str
        """

        self._id = id

    @property
    def host(self) -> str:
        """Gets the host of this FriendrequestFriend.


        :return: The host of this FriendrequestFriend.
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host: str):
        """Sets the host of this FriendrequestFriend.


        :param host: The host of this FriendrequestFriend.
        :type host: str
        """

        self._host = host

    @property
    def display_name(self) -> str:
        """Gets the display_name of this FriendrequestFriend.


        :return: The display_name of this FriendrequestFriend.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: str):
        """Sets the display_name of this FriendrequestFriend.


        :param display_name: The display_name of this FriendrequestFriend.
        :type display_name: str
        """

        self._display_name = display_name

    @property
    def url(self) -> str:
        """Gets the url of this FriendrequestFriend.


        :return: The url of this FriendrequestFriend.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this FriendrequestFriend.


        :param url: The url of this FriendrequestFriend.
        :type url: str
        """

        self._url = url
