# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .util import *


class InlineResponse2005(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, query: str=None, authors: List[str]=None):  # noqa: E501
        """InlineResponse2005 - a model defined in Swagger

        :param query: The query of this InlineResponse2005.  # noqa: E501
        :type query: str
        :param authors: The authors of this InlineResponse2005.  # noqa: E501
        :type authors: List[str]
        """
        self.swagger_types = {
            'query': str,
            'authors': List[str]
        }

        self.attribute_map = {
            'query': 'query',
            'authors': 'authors'
        }
        self._query = query
        self._authors = authors

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5 of this InlineResponse2005.  # noqa: E501
        :rtype: InlineResponse2005
        """
        return util.deserialize_model(dikt, cls)

    @property
    def query(self) -> str:
        """Gets the query of this InlineResponse2005.


        :return: The query of this InlineResponse2005.
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query: str):
        """Sets the query of this InlineResponse2005.


        :param query: The query of this InlineResponse2005.
        :type query: str
        """

        self._query = query

    @property
    def authors(self) -> List[str]:
        """Gets the authors of this InlineResponse2005.


        :return: The authors of this InlineResponse2005.
        :rtype: List[str]
        """
        return self._authors

    @authors.setter
    def authors(self, authors: List[str]):
        """Sets the authors of this InlineResponse2005.


        :param authors: The authors of this InlineResponse2005.
        :type authors: List[str]
        """

        self._authors = authors
