# Generated by Django 2.2.9 on 2020-02-19 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('source', models.URLField()),
                ('origin', models.URLField()),
                ('description', models.CharField(max_length=512)),
                ('contentType', models.CharField(choices=[('Text', (('text/plain', 'plain text'), ('text/markdown', 'markdown'))), ('Image', (('image/png;base64', 'png'), ('image/jpeg;base64', 'jpeg'))), ('application/base64', 'base64 encoded')], default='text/markdown', max_length=32)),
                ('content', models.TextField()),
                ('size', models.PositiveIntegerField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FOAF', 'Friends of Friends'), ('FRIENDS', 'Friends'), ('PRIVATE', 'Private'), ('SERVERONLY', 'Server Admins Only')], default='FRIENDS', max_length=16)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='posts.Category')),
                ('visibleTo', models.ManyToManyField(blank=True, related_name='posts_granted_access_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
