# Generated by Django 2.2.10 on 2020-04-01 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200222_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visibleTo',
        ),
        migrations.CreateModel(
            name='VisibleTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_uid', models.CharField(max_length=500)),
                ('accessed_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibleTo', to='posts.Post')),
            ],
        ),
    ]
